-- ---------------------------------------------------------------------------
-- Phase 6 — FAQ content (PROJECT_PLAN.md)
--
-- Replaces the Alam FAQs and FAQ categories with the /ci3/ FAQ page, and sets
-- the FAQ page (Web Pages 6) hero, sections and meta. The hidden "Home Page"
-- category (cat_id 1) is kept, without questions.
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

DELETE FROM `faqs`;
DELETE FROM `faqs_categories` WHERE `cat_id` > 1;

INSERT INTO `faqs_categories` (`cat_id`, `cat_name`, `cat_short_description`, `cat_added`, `cat_updated`, `cat_order`, `cat_status`, `cat_hidden`) VALUES (2, 'Appointments', 'Booking, changing and arriving.', NOW(), NOW(), 2, 'Enable', 'No');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (1, 'How do I book an appointment?', 'Book online through the booking page, or call the salon on +48 512 129 654 during opening hours. Online booking lets you pick your service, your artist and a time in one go.', 2, NOW(), NOW(), 1, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (2, 'Can I reschedule my appointment?', 'Yes — the easiest way is to call us so we can find you another slot straight away. Placeholder: the notice period for rescheduling has not been set yet, so please check with the salon.', 2, NOW(), NOW(), 2, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (3, 'How do I cancel?', 'Call the salon and we will take care of it. Placeholder: Blossom''s cancellation notice period, deposit and refund rules have not been confirmed, so nothing specific is stated here yet.', 2, NOW(), NOW(), 3, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (4, 'How early should I arrive?', 'A few minutes before your slot is plenty — it gives us time to talk through what you would like before we start. Placeholder: the salon has not set a policy for late arrivals.', 2, NOW(), NOW(), 4, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (5, 'Can I book more than one service in a visit?', 'Yes. Choose everything you want in the booking flow and it will add the durations together, so the time set aside matches what you have booked.', 2, NOW(), NOW(), 5, 'Enable');
INSERT INTO `faqs_categories` (`cat_id`, `cat_name`, `cat_short_description`, `cat_added`, `cat_updated`, `cat_order`, `cat_status`, `cat_hidden`) VALUES (3, 'Nails', 'Manicure, gel and nail art.', NOW(), NOW(), 3, 'Enable', 'No');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (6, 'How long does a manicure take?', 'A classic manicure is around an hour. A gel manicure is closer to 75 minutes, and extensions take 90 minutes to two hours depending on the length and shape.', 3, NOW(), NOW(), 1, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (7, 'How long does a gel manicure last?', 'Usually two to three weeks before regrowth starts to show. How long it stays perfect depends a lot on your nails and what you do with your hands day to day.', 3, NOW(), NOW(), 2, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (8, 'Can I bring nail art inspiration?', 'Please do. Screenshots are ideal, and two or three photos are more useful than one because they show what you consistently like.', 3, NOW(), NOW(), 3, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (9, 'Can nail art be added to any manicure?', 'Yes, art can be added to a classic or gel manicure and to extensions. It is priced per nail, so mention it when you book and we will set aside the extra time.', 3, NOW(), NOW(), 4, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (10, 'Do you remove gel applied somewhere else?', 'Yes. Let us know when you book so we can allow time for removal before your new set.', 3, NOW(), NOW(), 5, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (11, 'What if a nail breaks before my next appointment?', 'Give us a call. A single nail can often be repaired quickly rather than needing the whole set redone.', 3, NOW(), NOW(), 6, 'Enable');
INSERT INTO `faqs_categories` (`cat_id`, `cat_name`, `cat_short_description`, `cat_added`, `cat_updated`, `cat_order`, `cat_status`, `cat_hidden`) VALUES (4, 'The salon', 'Finding us, hours and payment.', NOW(), NOW(), 4, 'Enable', 'No');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (12, 'Do you accept walk-ins?', 'Booking ahead is the only way to be sure of a slot, since appointments are spaced to avoid rushing. If you are passing, call first and we will tell you honestly whether there is space.', 4, NOW(), NOW(), 1, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (13, 'Where is Blossom?', '2 Piekarska Street, 38-300 Gorlice, in the centre of town. We are on the floor above the 5.10.15 children''s store.', 4, NOW(), NOW(), 2, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (14, 'What are your opening hours?', 'Monday to Friday, 9:00 AM to 5:00 PM. Saturday, 9:00 AM to 2:00 PM. Closed on Sunday.', 4, NOW(), NOW(), 3, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (15, 'How can I pay?', 'Placeholder: the payment methods Blossom accepts have not been confirmed yet. Please ask when you book.', 4, NOW(), NOW(), 4, 'Enable');
INSERT INTO `faqs` (`faq_id`, `faq_question`, `faq_answer`, `faq_cat_id`, `faq_added`, `faq_updated`, `faq_order`, `faq_status`) VALUES (16, 'Is there parking nearby?', 'Placeholder: parking details for Piekarska Street have not been confirmed yet.', 4, NOW(), NOW(), 5, 'Enable');

UPDATE `pages` SET
    `banner_title` = 'Good to know',
    `banner_heading` = 'Questions we''re asked a lot',
    `banner_text` = 'Booking, nails and finding the salon. If yours isn''t here, give us a call — we''d rather answer properly than guess.',
    `banner_background` = '',
    `meta_description` = 'Common questions about booking, manicures, gel nails and visiting Blossom Ewa Mazur in Gorlice.'
WHERE `page_id` = 6;

DELETE FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` NOT IN ('sidebar', 'questions', 'links', 'cta');

INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 6, 'sidebar', 'Sidebar', 10, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'sidebar');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'On this page' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'sidebar' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'help_heading', 'Still stuck?' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'sidebar' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'help_text', 'We answer the phone during opening hours.' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'sidebar' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 6, 'questions', 'Questions', 20, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'questions');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'note', 'Answers marked as placeholders are deliberately vague — Blossom hasn''t set cancellation windows, deposits or refund rules yet, and we would rather say so than invent them.' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'questions' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 6, 'links', 'Prices and Policies', 30, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Looking for prices?' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Every service is listed with its own price and how long it takes.' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_1_text', 'View services' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_1_url', 'services' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_2_text', 'Cancellation policy' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_2_url', 'cancellation-policy' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'links' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 6, 'cta', 'Call to Action', 40, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'cta');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Book your visit to Blossom' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Pick a time that suits you and tell us what you have in mind. First visit? Let us know when you book and we''ll leave extra time to talk it through.' FROM `web_page_sections` WHERE `page_id` = 6 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
