-- ---------------------------------------------------------------------------
-- Phase 6 — Services content (PROJECT_PLAN.md)
--
-- The service categories, 14 services (prices, durations, texts, add-ons,
-- related services) and the Nail Shapes & Finishes block, taken from the
-- /ci3/ reference pages. Run after phase-6-services.sql.
--
-- It replaces all services and service categories, so run it only on a
-- database without real service data. The image file names are uploads in
-- assets/frontend/images/services/ (not in the repository); on another
-- environment, upload the images through Manage > Services instead.
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

-- Categories and services ----------------------------------------------------

DELETE FROM `services`;
DELETE FROM `service_categories`;

INSERT INTO `service_categories` (`category_id`, `category_name`, `category_slug`, `category_heading`, `category_description`, `category_order`, `category_status`, `category_added`, `category_updated`) VALUES (1, 'Nails', 'nails', NULL, 'Manicure, gel, extensions and hand-painted nail art — what we do most.', 1, 'Enable', NOW(), NOW());
INSERT INTO `service_categories` (`category_id`, `category_name`, `category_slug`, `category_heading`, `category_description`, `category_order`, `category_status`, `category_added`, `category_updated`) VALUES (2, 'Hair', 'hair', NULL, 'Cuts, styling, colour and care, booked on their own or with nails.', 2, 'Enable', NOW(), NOW());
INSERT INTO `service_categories` (`category_id`, `category_name`, `category_slug`, `category_heading`, `category_description`, `category_order`, `category_status`, `category_added`, `category_updated`) VALUES (3, 'Beauty', 'beauty', NULL, 'Facials, makeup, brows and waxing in the same relaxed studio.', 3, 'Enable', NOW(), NOW());

INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (1, 1, 'Manicure', 'manicure', 'Classic or combined manicure — cuticle work, shaping and a smooth, even finish. Choose a natural look or a colour you love.', '<p>Our most-booked service and the base everything else is built on. We tidy the cuticles, shape the free edge to the length you like, and finish with a buff or a colour of your choosing.</p>', '80', '', '60 min', 60, 'efcd7c7abacc9df320dd2588d5c63d60.jpg', 'efcd7c7abacc9df320dd2588d5c63d60.jpg', 'Cuticle care and nail shaping\nLight buff and surface smoothing\nRegular polish or a bare, natural finish\nHand cream and a short hand massage', 'Come with clean, product-free nails if you can\nBring a colour or photo if you already have one in mind', 'Give regular polish a couple of hours before anything rough\nCuticle oil daily keeps the finish looking fresh for longer', 1, 1, 'Manicure | Blossom Ewa Mazur', 'Classic or combined manicure — cuticle work, shaping and a smooth, even finish. Choose a natural look or a colour you love. From 80 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 1, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (2, 1, 'Gel Manicure', 'gel-manicure', 'A full manicure finished in gel colour — long-wearing, glossy, and kind to the nail underneath.', '<p>The same careful prep as a classic manicure, finished with gel colour cured under lamp. It keeps its shine far longer than regular polish and is the one most clients come back for.</p>', '120', '', '75 min', 75, 'd0ce28377ff9be4b76002f3776eb547f.jpg', 'd0ce28377ff9be4b76002f3776eb547f.jpg', 'Full manicure and cuticle preparation\nGel base, colour and top coat\nShaping to the length you prefer\nRemoval of existing gel where needed', 'Let us know at booking if you have gel on that needs removing', 'Cuticle oil daily keeps the gel flexible and the skin comfortable\nCome back for removal rather than peeling it off — peeling takes the top layer of the nail with it', 1, 1, 'Gel Manicure | Blossom Ewa Mazur', 'A full manicure finished in gel colour — long-wearing, glossy, and kind to the nail underneath. From 120 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 2, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (3, 1, 'Nail Art', 'nail-art', 'Hand-painted designs, from a single fine line to a full set. Bring a photo you like or plan it together at the table.', '<p>Everything here is painted by hand, one nail at a time. Minimal lines, French variations, chrome, marble or something seasonal — we work out the design with you before anything is painted.</p>', '20', '/ nail', '+30 min', 30, '603a796a22930ebed85292ca424ef10b.jpg', '603a796a22930ebed85292ca424ef10b.jpg', 'Design planned with you before we start\nHand-painted detail, priced per nail\nChoice of finish — matte, gloss, chrome or pearl\nAdded to any manicure or gel service', 'Save a few reference photos — screenshots are perfect\nBook a little extra time if you want art on every nail', 'A gloss or matte top coat refresh keeps the design sharp', 1, 1, 'Nail Art | Blossom Ewa Mazur', 'Hand-painted designs, from a single fine line to a full set. Bring a photo you like or plan it together at the table. From 20 zł / nail at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 3, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (4, 1, 'Nail Extensions', 'nail-extensions', 'Gel extensions in the length and shape that suit your hands, with refills when you need them.', '<p>Builder gel and extensions for extra length, shaped to almond, square, oval or coffin. We talk through what will actually be comfortable for your hands and how you use them before choosing a length.</p>', '140', '', '90–120 min', 120, '9807e290d001a485b35a9db646a2489b.jpg', '9807e290d001a485b35a9db646a2489b.jpg', 'Full preparation and cuticle work\nGel extension to your chosen length and shape\nColour or a natural finish\nShape advice for your nail bed', 'Allow a little longer than a standard appointment\nThink about the length you can live with day to day', 'Refills every three to four weeks keep the shape balanced\nBook removal with us rather than taking them off at home', 1, 1, 'Nail Extensions | Blossom Ewa Mazur', 'Gel extensions in the length and shape that suit your hands, with refills when you need them. From 140 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 4, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (5, 1, 'Nail Styling', 'nail-styling', 'Shape, length and finish planned around your hands — the consultation that makes everything else fit.', '<p>A sit-down about what actually suits you: nail shape, length, colour direction and finish. Useful before a first gel set, an event, or if you have never quite settled on a shape.</p>', '60', '', '30 min', 30, '71cb0c0e9b87f7f7c318eef6faac7f56.jpg', '71cb0c0e9b87f7f7c318eef6faac7f56.jpg', 'Shape and length consultation\nColour and finish direction\nShade matching against your skin tone\nA plan for your next few appointments', 'Bring any photos of sets you have liked or disliked', '', 0, 1, 'Nail Styling | Blossom Ewa Mazur', 'Shape, length and finish planned around your hands — the consultation that makes everything else fit. From 60 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 5, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (6, 1, 'Nail Care & Repair', 'nail-care', 'Gentle care for weak, peeling or bitten nails, plus hand care and advice for between visits.', '<p>For nails that need a bit of looking after rather than covering up. We keep the work gentle, tidy what is there, and talk through a simple routine to follow at home.</p>', '70', '', '45 min', 45, 'd6b02bbdc27e2d8704f77b07e40854d6.jpg', 'd6b02bbdc27e2d8704f77b07e40854d6.jpg', 'Gentle shaping and cuticle care\nSingle-nail repair where possible\nNourishing treatment and hand care\nA simple at-home routine to follow', 'Come as you are — there is nothing to tidy up beforehand', 'Cuticle oil daily is the single most useful habit\nGive the nails a few weeks between gel sets if they feel weak', 0, 1, 'Nail Care & Repair | Blossom Ewa Mazur', 'Gentle care for weak, peeling or bitten nails, plus hand care and advice for between visits. From 70 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 6, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (7, 2, 'Haircut', 'haircut', 'A cut shaped to how you actually wear your hair day to day.', '<p>We start by talking about how you style your hair at home, then cut to suit that rather than to suit a photo you will never recreate.</p>', '90', '', '60 min', 60, '97855de9edb5b83acd7907627b0d29fe.jpg', '97855de9edb5b83acd7907627b0d29fe.jpg', 'Consultation\nWash and cut\nFinish and style', '', '', 0, 0, 'Haircut | Blossom Ewa Mazur', 'A cut shaped to how you actually wear your hair day to day. From 90 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 7, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (8, 2, 'Hair Styling', 'hair-styling', 'Blow-dry, waves or an occasion style for weddings and events.', '<p>Styling for a specific day — a birthday, a wedding, or just because. Tell us what you are dressing for and we will work to that.</p>', '80', '', '45 min', 45, 'dfe5cbd36483eb4bbd49abd88080efa1.jpg', 'dfe5cbd36483eb4bbd49abd88080efa1.jpg', 'Wash and prep\nBlow-dry or set\nFinish that holds all day', '', '', 0, 0, 'Hair Styling | Blossom Ewa Mazur', 'Blow-dry, waves or an occasion style for weddings and events. From 80 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 8, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (9, 2, 'Hair Colour', 'hair-color', 'Full colour, root touch-ups and grey coverage.', '<p>Colour matched in daylight and applied with your regrowth in mind, so it stays wearable as it grows out.</p>', '160', '', '120 min', 120, '97855de9edb5b83acd7907627b0d29fe.jpg', '97855de9edb5b83acd7907627b0d29fe.jpg', 'Colour consultation and shade match\nApplication and development\nWash, condition and finish', 'A patch test may be needed before your appointment — we will confirm when you book', '', 0, 0, 'Hair Colour | Blossom Ewa Mazur', 'Full colour, root touch-ups and grey coverage. From 160 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 9, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (10, 2, 'Hair Treatments', 'hair-treatments', 'Conditioning and scalp treatments for dry or tired hair.', '<p>A treatment chosen after we look at your hair and scalp, added to a cut or booked on its own.</p>', '70', '', '40 min', 40, 'dfe5cbd36483eb4bbd49abd88080efa1.jpg', 'dfe5cbd36483eb4bbd49abd88080efa1.jpg', 'Hair and scalp assessment\nTreatment application\nFinish', '', '', 0, 0, 'Hair Treatments | Blossom Ewa Mazur', 'Conditioning and scalp treatments for dry or tired hair. From 70 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 10, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (11, 3, 'Facial & Skin Care', 'facial-skin-care', 'Facials chosen to suit your skin, with no rushing.', '<p>We look at your skin first and pick the treatment from there. Expect an unhurried hour and straightforward advice rather than a product list.</p>', '120', '', '60 min', 60, 'f8fb0fa080449073cd6cbf8a6ca206e9.jpg', 'f8fb0fa080449073cd6cbf8a6ca206e9.jpg', 'Skin consultation\nCleanse, exfoliate and treatment mask\nMassage and finishing care', 'Come without makeup if that suits your day', 'Keep sun exposure gentle for a day or two afterwards', 0, 0, 'Facial & Skin Care | Blossom Ewa Mazur', 'Facials chosen to suit your skin, with no rushing. From 120 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 11, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (12, 3, 'Makeup', 'makeup', 'Makeup for weddings, events and photographs.', '<p>Shade-matched in daylight and built to last the length of the day, whether that is a ceremony or a evening out.</p>', '150', '', '60 min', 60, '9d3d5916b4ee67ad8bec21af38d72b3a.jpg', '9d3d5916b4ee67ad8bec21af38d72b3a.jpg', 'Shade matching\nFull application\nTouch-up advice', 'Arrive with clean, moisturised skin', '', 0, 0, 'Makeup | Blossom Ewa Mazur', 'Makeup for weddings, events and photographs. From 150 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 12, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (13, 3, 'Waxing & Hair Removal', 'waxing', 'Brow shaping, facial and body waxing.', '<p>Quick, careful and private. Brow shaping is the one most often added to a nail appointment.</p>', '60', '', '30 min', 30, 'ac1dbfadb18c12360a0d5e71fb850eb6.jpg', 'ac1dbfadb18c12360a0d5e71fb850eb6.jpg', 'Consultation on shape\nWaxing\nSoothing aftercare', '', 'Skip heat, swimming and sunbeds for 24 hours', 0, 0, 'Waxing & Hair Removal | Blossom Ewa Mazur', 'Brow shaping, facial and body waxing. From 60 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 13, 'Enable', NOW(), NOW());
INSERT INTO `services` (`service_id`, `service_category_id`, `service_name`, `service_slug`, `service_summary`, `service_description`, `service_price_from`, `service_price_suffix`, `service_duration_label`, `service_duration_minutes`, `service_card_image`, `service_hero_image`, `service_included`, `service_before_visit`, `service_aftercare`, `service_featured`, `service_show_shapes`, `page_title`, `meta_description`, `robots_index`, `robots_follow`, `og_title`, `og_description`, `og_image`, `service_order`, `service_status`, `service_added`, `service_updated`) VALUES (14, 3, 'Beauty Treatments', 'beauty-treatments', 'Brow tinting, lashes and other finishing touches.', '<p>The smaller treatments that tend to get booked alongside something else — brows, lashes and general tidying up before an event.</p>', '50', '', '30 min', 30, 'b3bd52b297d21bb462b2d694f1b95478.jpg', 'b3bd52b297d21bb462b2d694f1b95478.jpg', 'Consultation\nTreatment\nAftercare advice', '', '', 0, 0, 'Beauty Treatments | Blossom Ewa Mazur', 'Brow tinting, lashes and other finishing touches. From 50 zł at Blossom Ewa Mazur in Gorlice.', 1, 1, '', '', NULL, 14, 'Enable', NOW(), NOW());

-- Add-ons ---------------------------------------------------------------------

INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (1, 'Gel colour instead of regular polish', '40', 1);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (1, 'Art on two accent nails', '40', 2);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (1, 'Extended hand massage', '25', 3);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (2, 'French finish', '30', 1);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (2, 'Art on two accent nails', '40', 2);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (2, 'Chrome or pearl top', '30', 3);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (3, 'Art across all ten nails', '150', 1);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (3, 'Chrome or pearl finish', '30', 2);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (3, 'Seasonal design', '60', 3);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (4, 'Refill', '110', 1);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (4, 'Soak-off removal', '40', 2);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (4, 'Art on accent nails', '40', 3);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (5, 'Combined with a manicure', '80', 1);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (6, 'Paraffin hand treatment', '45', 1);
INSERT INTO `service_addons` (`addon_service_id`, `addon_label`, `addon_price`, `addon_order`) VALUES (12, 'Trial before the day', '100', 1);

-- Often booked with this --------------------------------------------------------

INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (1, 2);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (1, 3);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (1, 6);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (2, 1);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (2, 3);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (2, 4);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (3, 2);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (3, 5);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (3, 4);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (4, 2);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (4, 3);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (4, 6);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (5, 1);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (5, 3);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (5, 2);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (6, 1);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (6, 5);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (6, 2);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (7, 8);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (7, 9);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (7, 10);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (8, 7);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (8, 12);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (8, 9);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (9, 7);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (9, 10);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (9, 8);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (10, 7);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (10, 9);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (10, 8);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (11, 12);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (11, 13);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (11, 14);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (12, 11);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (12, 8);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (12, 14);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (13, 11);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (13, 12);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (13, 14);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (14, 13);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (14, 12);
INSERT INTO `service_related` (`service_id`, `related_service_id`) VALUES (14, 11);

-- Nail Shapes & Finishes (Manage > Miscellaneous Contents) --------------------

INSERT INTO `miscellaneous_content_sections` (`section_key`, `section_label`, `status`)
SELECT 'nail_shapes_finishes', 'Nail Shapes & Finishes', 'Enable'
WHERE NOT EXISTS (
    SELECT 1 FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes'
);

INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Choose your look' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Shapes and finishes' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Nothing is decided before you arrive — we go through this together at the start of the appointment.' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'shapes_heading', 'Shapes' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'shapes', 'Almond | Soft and lengthening\nSquare | Clean and sturdy\nSquoval | Square with softened corners\nOval | The most forgiving on short nails\nCoffin | Needs a little length' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'finishes_heading', 'Finishes' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'finishes', 'Minimal | Clean, simple and easy to wear every day. | #EFE2EC\nFrench | The classic tip, in white or any colour you like. | #F4CFF0\nChrome | Mirror and pearl finishes with a soft shine. | #CFC7D8\nCreative | Hand-painted designs, made just for you. | #C049B3\nBold colour | Bright, confident shades that stand out. | #952F89\nSeasonal | Warmer, deeper tones for autumn and winter. | #41163C' FROM `miscellaneous_content_sections` WHERE `section_key` = 'nail_shapes_finishes' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);

-- Services listing page (Web Pages > Services) ---------------------------------

UPDATE `pages` SET
    `banner_title` = 'Our services',
    `banner_heading` = 'Everything we do, and what it costs',
    `banner_text` = 'Nails lead the list — manicure, gel, art, extensions and care. Hair, skin, makeup and waxing follow, and any of them can be booked together in one visit.',
    `banner_background` = 'fced6be36ba3a0eb9a7d389a9e4d5346.jpg',
    `meta_description` = 'Manicure, gel nails, nail art, extensions and nail care at Blossom in Gorlice, alongside hair, facials, makeup and waxing. Prices and durations for every service.'
WHERE `page_id` = 37;

INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 37, 'featured_services', 'Featured Services', 10, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'featured_services');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Where we spend most of our time' FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'featured_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Nail services' FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'featured_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 37, 'full_menu', 'Full Menu', 20, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'full_menu');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'The full menu' FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'full_menu' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Prices start from the amounts shown — the final total depends on length, shape and how much design you would like.' FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'full_menu' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 37, 'cta', 'Call to Action', 30, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'cta');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Not sure which one you need?' FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Book a manicure and we''ll work it out together at the table, or call the salon and we''ll talk it through first.' FROM `web_page_sections` WHERE `page_id` = 37 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);

-- Service Page labels (Manage > Miscellaneous Contents) ------------------------

INSERT INTO `miscellaneous_content_sections` (`section_key`, `section_label`, `status`)
SELECT 'service_page', 'Service Page', 'Enable'
WHERE NOT EXISTS (SELECT 1 FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page');

INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'included_heading', 'What''s included' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'before_heading', 'Before your visit' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'aftercare_heading', 'Looking after it' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'addons_heading', 'Add to this appointment' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'addons_note', 'Mention any of these when you book and we''ll set aside the extra time.' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'gallery_heading', 'Sets like this' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'artists_heading', 'Who takes this appointment' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'related_heading', 'Often booked with this' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'cta_heading', 'Ready to book your {service}?' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `miscellaneous_content_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'cta_text', 'Pick a time that works for you. If you''d rather talk it through first, give the salon a call.' FROM `miscellaneous_content_sections` WHERE `section_key` = 'service_page' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
