-- ---------------------------------------------------------------------------
-- Phase 6 — Journal content (PROJECT_PLAN.md)
--
-- Replaces the Alam blog posts and categories with the /ci3/ journal
-- articles, and sets the Journal page (Web Pages 8) hero, sections and meta.
-- Requires docs/sql/phase-6-journal.sql (blogs.blog_service_id).
--
-- The image file names are uploads (not in the repository); on another
-- environment, upload the images through the admin instead.
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

DELETE FROM `blog_assigned_cat`;
DELETE FROM `blogs`;
DELETE FROM `blog_categories` WHERE `cat_id` > 1;

INSERT INTO `blog_categories` (`cat_id`, `cat_name`, `cat_slug`, `cat_desc`, `cat_added`, `cat_updated`, `cat_status`, `cat_order`) VALUES (2, 'Nail Care', 'nail-care', '', NOW(), NOW(), 'Enable', 1);
INSERT INTO `blog_categories` (`cat_id`, `cat_name`, `cat_slug`, `cat_desc`, `cat_added`, `cat_updated`, `cat_status`, `cat_order`) VALUES (3, 'Nail Art', 'nail-art', '', NOW(), NOW(), 'Enable', 2);
INSERT INTO `blog_categories` (`cat_id`, `cat_name`, `cat_slug`, `cat_desc`, `cat_added`, `cat_updated`, `cat_status`, `cat_order`) VALUES (4, 'Manicure', 'manicure', '', NOW(), NOW(), 'Enable', 3);
INSERT INTO `blog_categories` (`cat_id`, `cat_name`, `cat_slug`, `cat_desc`, `cat_added`, `cat_updated`, `cat_status`, `cat_order`) VALUES (5, 'Beauty Tips', 'beauty-tips', '', NOW(), NOW(), 'Enable', 4);
INSERT INTO `blog_categories` (`cat_id`, `cat_name`, `cat_slug`, `cat_desc`, `cat_added`, `cat_updated`, `cat_status`, `cat_order`) VALUES (6, 'Salon News', 'salon-news', '', NOW(), NOW(), 'Enable', 5);

INSERT INTO `blogs` (`blog_id`, `blog_slug`, `blog_name`, `blog_short_description`, `blog_author`, `blog_service_id`, `blog_time_to_read`, `blog_image`, `blog_text`, `blog_added`, `blog_updated`, `blog_year`, `blog_month`, `blog_month_year`, `blog_status`, `blog_pdate`, `blog_featured`, `meta_description`) VALUES (1, 'autumn-shades-at-blossom', 'Autumn shades on the shelf', 'The deeper end of the colour shelf comes into its own around now — plums, warm browns and near-blacks.', (SELECT MIN(`id`) FROM `admin_users`), (SELECT `service_id` FROM `services` WHERE `service_slug` = 'gel-manicure'), 2, 'fc94baf365bec406808f7b70e43ef149.jpg', '<p>Every year around this time the pastels get quieter and the deeper shades start getting asked for. Plum, warm brown and a near-black that reads as navy in some light are the ones moving fastest at the moment.</p>\n<p>They suit a shorter almond set particularly well — deep colour on a short nail looks considered rather than heavy.</p>\n<figure>\n<img src="/assets/uploads/images/74354d7c4d821276da3c8633da05d3b6.jpg" alt="Bottles of nail lacquer in green, orange, yellow, red and grey">\n<figcaption>The colour shelf, restocked for the season.</figcaption>\n</figure>', '2026-05-08 09:00:00', '2026-05-08 09:00:00', 2026, 5, '2026-05', 'Published', '2026-05-08 09:00:00', 'No', 'The deeper end of the colour shelf comes into its own around now — plums, warm browns and near-blacks.');
INSERT INTO `blog_assigned_cat` (`bc_cat_id`, `bc_blog_id`) VALUES (6, 1);
INSERT INTO `blogs` (`blog_id`, `blog_slug`, `blog_name`, `blog_short_description`, `blog_author`, `blog_service_id`, `blog_time_to_read`, `blog_image`, `blog_text`, `blog_added`, `blog_updated`, `blog_year`, `blog_month`, `blog_month_year`, `blog_status`, `blog_pdate`, `blog_featured`, `meta_description`) VALUES (2, 'getting-ready-for-an-event', 'Getting ready for a wedding or event', 'How far ahead to book nails, hair and makeup so nothing is rushed on the day.', (SELECT MIN(`id`) FROM `admin_users`), (SELECT `service_id` FROM `services` WHERE `service_slug` = 'makeup'), 3, '896dccdaf5b2a53cdf8cd37b8a6f859d.jpg', '<p>The most common mistake is booking everything for the morning of the event. Spreading it out makes the day far calmer.</p>\n<h2>A rough order</h2>\n<ul>\n<li>Nails: two or three days before, so any adjustment is possible</li>\n<li>Hair colour: two weeks before, so it has settled</li>\n<li>Makeup trial: a few weeks before, in daylight if you can</li>\n<li>Hair styling and makeup: on the day</li>\n</ul>\n<p>Mention the event when you book. It changes how much time we set aside and how we plan the appointment.</p>', '2026-05-22 09:00:00', '2026-05-22 09:00:00', 2026, 5, '2026-05', 'Published', '2026-05-22 09:00:00', 'No', 'How far ahead to book nails, hair and makeup so nothing is rushed on the day.');
INSERT INTO `blog_assigned_cat` (`bc_cat_id`, `bc_blog_id`) VALUES (5, 2);
INSERT INTO `blogs` (`blog_id`, `blog_slug`, `blog_name`, `blog_short_description`, `blog_author`, `blog_service_id`, `blog_time_to_read`, `blog_image`, `blog_text`, `blog_added`, `blog_updated`, `blog_year`, `blog_month`, `blog_month_year`, `blog_status`, `blog_pdate`, `blog_featured`, `meta_description`) VALUES (3, 'looking-after-weak-nails', 'Looking after weak or peeling nails', 'If your nails are splitting or peeling, a break from gel is only part of the answer.', (SELECT MIN(`id`) FROM `admin_users`), (SELECT `service_id` FROM `services` WHERE `service_slug` = 'nail-care'), 4, '2996049f5ea637c12a3c488e2d42c604.jpg', '<p>Weak nails are common and usually fixable with patience rather than a product. The frustrating part is that it takes a few months, because you are waiting for new growth.</p>\n<h2>Keep them short for a while</h2>\n<p>Length is leverage. A shorter nail has far less opportunity to catch, bend and split, which gives the new growth a chance to come through undamaged.</p>\n<h2>Oil, consistently</h2>\n<p>Cuticle oil once a day does more over a month than any single treatment does in one appointment. Keep a bottle somewhere you will actually see it.</p>\n<p>If you would like a hand with it, book a nail care appointment and we will look at what is going on and put together a simple routine.</p>', '2026-06-12 09:00:00', '2026-06-12 09:00:00', 2026, 6, '2026-06', 'Published', '2026-06-12 09:00:00', 'No', 'If your nails are splitting or peeling, a break from gel is only part of the answer.');
INSERT INTO `blog_assigned_cat` (`bc_cat_id`, `bc_blog_id`) VALUES (2, 3);
INSERT INTO `blogs` (`blog_id`, `blog_slug`, `blog_name`, `blog_short_description`, `blog_author`, `blog_service_id`, `blog_time_to_read`, `blog_image`, `blog_text`, `blog_added`, `blog_updated`, `blog_year`, `blog_month`, `blog_month_year`, `blog_status`, `blog_pdate`, `blog_featured`, `meta_description`) VALUES (4, 'bringing-nail-art-inspiration', 'Bringing nail art inspiration to your appointment', 'Screenshots are welcome. Here is what makes a reference photo genuinely useful to work from.', (SELECT MIN(`id`) FROM `admin_users`), (SELECT `service_id` FROM `services` WHERE `service_slug` = 'nail-art'), 3, '1f7b0f1ade2bed14437f894e1e8b9f4c.jpg', '<p>Bring photos. Honestly, bring lots of them — it is far easier to work from a picture than from a description, and nobody minds a camera roll full of saved nail sets.</p>\n<h2>What helps most</h2>\n<ul>\n<li>Two or three photos rather than one, so we can see what you consistently like</li>\n<li>A note on what specifically appeals — the colour, the shape, the detail</li>\n<li>Any photo of a set you disliked, which is often more useful</li>\n</ul>\n<h2>A small note on scale</h2>\n<p>Designs in photos are often painted on longer nails than the ones you are wearing. Fine detail needs space, so on a shorter set we may simplify a design slightly to keep it clean rather than cramming it in.</p>\n<figure>\n<img src="/assets/uploads/images/0d0c48f89b199a95325d713c6d98949f.jpg" alt="Long almond nails in deep pink with hand-painted lettering">\n<figcaption>Longer sets carry more detail — shorter sets look better simplified.</figcaption>\n</figure>', '2026-06-30 09:00:00', '2026-06-30 09:00:00', 2026, 6, '2026-06', 'Published', '2026-06-30 09:00:00', 'No', 'Screenshots are welcome. Here is what makes a reference photo genuinely useful to work from.');
INSERT INTO `blog_assigned_cat` (`bc_cat_id`, `bc_blog_id`) VALUES (3, 4);
INSERT INTO `blogs` (`blog_id`, `blog_slug`, `blog_name`, `blog_short_description`, `blog_author`, `blog_service_id`, `blog_time_to_read`, `blog_image`, `blog_text`, `blog_added`, `blog_updated`, `blog_year`, `blog_month`, `blog_month_year`, `blog_status`, `blog_pdate`, `blog_featured`, `meta_description`) VALUES (5, 'choosing-a-nail-shape', 'Choosing a nail shape that suits your hands', 'Almond, square, oval or coffin — the right one depends on your nail bed and what you do all day.', (SELECT MIN(`id`) FROM `admin_users`), (SELECT `service_id` FROM `services` WHERE `service_slug` = 'nail-styling'), 5, '589481a91f1d0e602d4088ac91e915f6.jpg', '<p>Most people pick a nail shape from a photo and then quietly dislike it for three weeks. It is worth a couple of minutes at the start of an appointment to think about what will actually suit you.</p>\n<h2>Start with your nail bed</h2>\n<p>A short, wide nail bed tends to look longer with an almond or oval shape. A narrow bed carries square and squoval well. This matters more than the shape being fashionable.</p>\n<h2>Then think about your day</h2>\n<p>If you type all day, work with your hands, or have small children, a long coffin shape will annoy you by day three. There is no shame in a shorter set that you actually enjoy wearing.</p>\n<ul>\n<li>Almond — soft, lengthening, works at medium length</li>\n<li>Square — clean and sturdy, good on narrow beds</li>\n<li>Oval — the most forgiving on short nails</li>\n<li>Coffin — needs length, and needs you to be careful</li>\n</ul>\n<p>If you are unsure, book a nail styling appointment and we will work through it together before committing to anything.</p>', '2026-07-14 09:00:00', '2026-07-14 09:00:00', 2026, 7, '2026-07', 'Published', '2026-07-14 09:00:00', 'No', 'Almond, square, oval or coffin — the right one depends on your nail bed and what you do all day.');
INSERT INTO `blog_assigned_cat` (`bc_cat_id`, `bc_blog_id`) VALUES (4, 5);
INSERT INTO `blogs` (`blog_id`, `blog_slug`, `blog_name`, `blog_short_description`, `blog_author`, `blog_service_id`, `blog_time_to_read`, `blog_image`, `blog_text`, `blog_added`, `blog_updated`, `blog_year`, `blog_month`, `blog_month_year`, `blog_status`, `blog_pdate`, `blog_featured`, `meta_description`) VALUES (6, 'making-a-gel-manicure-last', 'Making a gel manicure last', 'Gel should stay glossy for weeks. If yours is lifting early, it is usually one of a few small habits.', (SELECT MIN(`id`) FROM `admin_users`), (SELECT `service_id` FROM `services` WHERE `service_slug` = 'gel-manicure'), 4, 'c1b4f109a77adb0e7d458aaae7356228.jpg', '<p>A gel manicure that lifts after a week is frustrating, and it is almost never the colour''s fault. Most of the time it comes down to what happens in the days after the appointment rather than during it.</p>\n<h2>Oil the cuticles daily</h2>\n<p>This is the single most useful habit. Cuticle oil keeps the skin around the nail comfortable and the gel flexible, and flexible gel is far less likely to catch and lift at the edges.</p>\n<h2>Be careful in the first day</h2>\n<p>Gel is cured before you leave, so it is hard straight away — but the bond keeps settling. Washing up in very hot water or picking at packaging in the first twenty-four hours does more damage than it seems.</p>\n<h2>Small things that help</h2>\n<ul>\n<li>Wear gloves for cleaning and washing up</li>\n<li>Use the pad of your finger, not your nail, to open things</li>\n<li>Book removal rather than peeling gel off at home</li>\n<li>Come back for a refill before the regrowth gets too obvious</li>\n</ul>\n<figure>\n<img src="/assets/uploads/images/873d8b784353915e139003af374a2add.jpg" alt="Short natural nails with a clean nude finish">\n<figcaption>A short, well-prepped nail holds gel better than a long one.</figcaption>\n</figure>\n<p>If your gel keeps lifting despite all of this, mention it at your next appointment. It is usually a prep or shape adjustment rather than anything you are doing wrong.</p>', '2026-07-28 09:00:00', '2026-07-28 09:00:00', 2026, 7, '2026-07', 'Published', '2026-07-28 09:00:00', 'No', 'Gel should stay glossy for weeks. If yours is lifting early, it is usually one of a few small habits.');
INSERT INTO `blog_assigned_cat` (`bc_cat_id`, `bc_blog_id`) VALUES (2, 6);

UPDATE `pages` SET
    `banner_title` = 'Journal',
    `banner_heading` = 'Notes from the studio',
    `banner_text` = 'Practical things we end up explaining at the table — how to make gel last, what shape will suit you, and how to plan for a big day.',
    `banner_background` = '',
    `meta_description` = 'Nail care, manicure and beauty notes from Blossom Ewa Mazur in Gorlice — making gel last, choosing a nail shape and getting ready for an event.'
WHERE `page_id` = 8;

DELETE FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` NOT IN ('articles', 'cta');

INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 8, 'articles', 'Articles', 10, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` = 'articles');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'More from the journal' FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` = 'articles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'note', 'These are sample articles written to design the layout. Blossom''s own posts will replace them.' FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` = 'articles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 8, 'cta', 'Call to Action', 20, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` = 'cta');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Book your visit to Blossom' FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Pick a time that suits you and tell us what you have in mind. First visit? Let us know when you book and we''ll leave extra time to talk it through.' FROM `web_page_sections` WHERE `page_id` = 8 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
