-- ---------------------------------------------------------------------------
-- Phase 6 — About page content (PROJECT_PLAN.md)
--
-- The About page (Web Pages 2): hero, page sections (replacing the Alam
-- sections) and meta, taken from the /ci3/ about page.
--
-- The image file names are uploads (not in the repository); on another
-- environment, upload the images through the admin instead.
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

UPDATE `pages` SET
    `banner_title` = 'About Blossom',
    `banner_heading` = 'Beauty and nail care in the heart of Gorlice',
    `banner_text` = 'Blossom Ewa Mazur is a small salon on Piekarska Street, just above the 5.10.15 store. Manicure and nail art are our speciality, with hair, skin, makeup and waxing alongside them.',
    `banner_background` = '736b46f9131f620f5cd3ce577e49fa9f.jpg',
    `meta_description` = 'Blossom Ewa Mazur is a small manicure and nail art salon on Piekarska Street in Gorlice, with hair, skin, makeup and waxing alongside.'
WHERE `page_id` = 2;

DELETE FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` NOT IN ('approach', 'nails_first', 'products', 'team', 'location', 'cta');

INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 2, 'approach', 'How We Work', 10, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'How we work' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'A small studio, and it shows' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'You are not queued, handed between people, or hurried to the door. Three things shape every appointment here.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_1_icon', 'fa-solid fa-wand-magic-sparkles' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_1_title', 'Attention to detail' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_1_text', 'Neat edges, clean lines and a finish that still looks right when you glance at your hands three days later.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_2_icon', 'fa-regular fa-hand' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_2_title', 'Made for your hands' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_2_text', 'Shape and length chosen around your nail bed and your day, not around whatever is in fashion this month.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_3_icon', 'fa-regular fa-heart' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_3_title', 'Time to talk it through' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_3_text', 'Appointments are spaced so nothing is rushed, and there is room to change your mind before we start.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'approach' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 2, 'nails_first', 'Nails First', 20, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Nails first' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'What we''re known for' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Manicure, gel and hand-painted nail art make up most of the diary. Every set starts with the preparation — the unglamorous half of the appointment, and the reason a finish lasts.\n\nThe rest of the menu grew around the people who kept asking for it: a facial before a wedding, brows added to a manicure, hair booked on the same afternoon.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_1_text', 'See nail services' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_1_url', 'services?category=nails' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_2_text', 'View the gallery' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_2_url', 'gallery' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_1', 'a875b2041777dc86f47ddf64c40877a3.jpg' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_2', '0c3d5495154659543c6920e09cdff419.jpg' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'nails_first' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 2, 'products', 'Products and Tools', 30, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'products');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Products and tools' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'products' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'We use professional salon products and keep the tools in good order. If you have a sensitivity or a preference, mention it when you book and we will work around it.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'products' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'note', 'Specific brands are not listed here yet — they will be added once the salon confirms what it would like named.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'products' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 2, 'team', 'Team', 40, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'team');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'The people behind the work' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'team' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Ewa runs the studio and takes most of the nail appointments herself.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'team' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_text', 'Meet the team' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'team' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 2, 'location', 'Location', 50, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'location');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Visit us' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'location' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Find us in Gorlice' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'location' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image', '6a0816fda3a408b741d1823a15feadc6.jpg' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'location' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 2, 'cta', 'Call to Action', 60, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'cta');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Book your visit to Blossom' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Pick a time that suits you and tell us what you have in mind. First visit? Let us know when you book and we''ll leave extra time to talk it through.' FROM `web_page_sections` WHERE `page_id` = 2 AND `section_key` = 'cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
