-- ---------------------------------------------------------------------------
-- Phase 6 — Home page content (PROJECT_PLAN.md)
--
-- The hero slides (Manage > Sliders > Home Page), the featured services
-- (shown on the home page and in the footer), the home page sections
-- (Web Pages > Home > Sections, replacing the Alam sections) and the home
-- page meta, taken from the /ci3/ home page. Run after the other
-- phase-6 content files.
--
-- The image file names are uploads (not in the repository); on another
-- environment, upload the images through the admin instead.
-- ---------------------------------------------------------------------------

SET NAMES utf8mb4;

-- Hero slides (slider group 6, the home page slider) ---------------------------

DELETE FROM `slider` WHERE `slider_id` = 6;

INSERT INTO `slider` (`slider_id`, `pre_heading`, `heading`, `text`, `button_1_icon`, `button_1_text`, `button_1_url`, `button_1_target`, `button_2_icon`, `button_2_text`, `button_2_url`, `button_2_target`, `image`, `overlay`, `status`, `order`, `created_at`, `updated_at`) VALUES (6, 'Manicure & nail art', 'Beautiful nails.|A little time for yourself.', 'Manicure and nail art in the centre of Gorlice, done in the style that suits you — in a calm little studio where nobody is rushed.', '', 'Book an appointment', 'book', '_self', 'fa-solid fa-arrow-right', 'See nail services', 'services?category=nails', '_self', '53e4a7d38e34a1038a9bf5623537cf5a.jpg', 'No', 'Enable', 1, NOW(), NOW());
INSERT INTO `slider` (`slider_id`, `pre_heading`, `heading`, `text`, `button_1_icon`, `button_1_text`, `button_1_url`, `button_1_target`, `button_2_icon`, `button_2_text`, `button_2_url`, `button_2_target`, `image`, `overlay`, `status`, `order`, `created_at`, `updated_at`) VALUES (6, 'Nail art', 'Nail art made around|your style', 'Fine lines, French, chrome or something seasonal — hand-painted in the shape, length and colour you like best.', '', 'Book nail art', 'book?service=nail-art', '_self', 'fa-solid fa-arrow-right', 'View the gallery', 'gallery', '_self', 'af23a80fbdc6c4a123c8e0486a27d4c7.jpg', 'No', 'Enable', 2, NOW(), NOW());
INSERT INTO `slider` (`slider_id`, `pre_heading`, `heading`, `text`, `button_1_icon`, `button_1_text`, `button_1_url`, `button_1_target`, `button_2_icon`, `button_2_text`, `button_2_url`, `button_2_target`, `image`, `overlay`, `status`, `order`, `created_at`, `updated_at`) VALUES (6, 'More at Blossom', 'Beauty treatments,|alongside your nails', 'Facials, brows, makeup and hair in the same relaxed studio. Book them with your manicure or on their own.', '', 'Book an appointment', 'book', '_self', 'fa-solid fa-arrow-right', 'All services', 'services', '_self', 'f8bb4e0664e4508f65099822ffad4466.jpg', 'No', 'Enable', 3, NOW(), NOW());

-- Featured services (home page and footer) ---------------------------------------

UPDATE `services` SET `service_featured` = IF(`service_slug` IN ('manicure', 'nail-art', 'nail-extensions', 'nail-care'), 1, 0);

-- Home page sections (Web Pages 1) ------------------------------------------------

DELETE FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` NOT IN ('hero', 'services_intro', 'other_services', 'nail_styles', 'gallery', 'about', 'artists', 'why', 'booking', 'offers', 'testimonials', 'location', 'instagram', 'final_cta');

INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'hero', 'Hero', 10, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'hero');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'finishes_note', 'Six nail finishes to choose from' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'hero' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'services_intro', 'Services', 20, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'services_intro');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Our services' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'services_intro' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Manicure and nail art,\nmade around you' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'services_intro' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Nails are what we do most at Blossom — manicure, gel, nail art and nail care. Hair, skin, makeup and waxing are here too, whether you book them on their own or add them to your nail appointment.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'services_intro' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_text', 'All nail services' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'services_intro' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_url', 'services?category=nails' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'services_intro' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'other_services', 'Other Services', 30, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Other beauty services' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Book them alongside your manicure, or on their own.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'link_text', 'View all services' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_1_title', 'Hair & Colour' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_1_text', 'Cuts, styling, colour and grey coverage.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_1_price', 'from 90 zł' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_1_url', 'services?category=hair' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_1_image', '6499ecf9c6463c5aceb7282f50515478.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_2_title', 'Facial & Skin' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_2_text', 'Facials and skin treatments, chosen to suit your skin.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_2_price', 'from 120 zł' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_2_url', 'services?category=beauty' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_2_image', 'cd2ef10bc4ae16f9928a9515b4ff5e64.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_3_title', 'Makeup & Waxing' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_3_text', 'Makeup for special days, brow shaping and waxing.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_3_price', 'from 60 zł' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_3_url', 'services?category=beauty' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'row_3_image', 'cfbd3c98fd7d850837caf094d11b4983.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'other_services' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'nail_styles', 'Nail Styles', 40, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Nail styles' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Nail art made personal' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Six styles we''re asked for most often. Choose the shape, colour and finish you like — something simple and minimal, something more creative, or a seasonal look. We''ll help you decide at the table.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_text', 'Explore nail services' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_url', 'services?category=nails' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_1', '9ba75d1a99f13b88a5e6abed21459be3.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_2', 'baba6565a4cb9d6bf1fd90e37154d2ea.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_3', '71a48dae5fde53f1f68300f630fbbbf2.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_4', 'b23a57713d489ae8f83b51373be05412.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_5', '18111ae156813eb83199295ced1ab60f.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_6', '2b530fac3e99efef53fceddce3fbe31b.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'nail_styles' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'gallery', 'Gallery', 50, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'gallery');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Recent work' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'gallery' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Fresh from the studio' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'gallery' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'A few of our favourite sets, photographed at Blossom.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'gallery' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'button_text', 'View gallery' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'gallery' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'about', 'About', 60, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'About Blossom' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Beauty and nail care in the heart of Gorlice' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Blossom Ewa Mazur is a small salon on Piekarska Street, just above the 5.10.15 store. Manicure and nail art are our speciality, with hair, skin, makeup and waxing alongside them. Every visit is unhurried, with real attention to the details you notice up close.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'point_1_title', 'Nails come first' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'point_1_text', 'Manicure, gel nails, nail art and nail care are what we do most, and what we love doing.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'point_2_title', 'Time to talk it through' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'point_2_text', 'We take time over shape, length and colour, so you leave with nails you actually wanted.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'point_3_title', 'A calm place to sit' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'point_3_text', 'A small studio, a quiet hour and your full attention on you — not a queue.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'link_text', 'More about Blossom' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_1', '71a48dae5fde53f1f68300f630fbbbf2.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_2', '1482b11177147947a10fb91123c9c9a4.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'about' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'artists', 'Artists', 70, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'artists');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Meet the team' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'artists' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'The people behind the work' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'artists' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Ewa takes most nail appointments herself. Book with someone in particular, or let us find you the next free slot.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'artists' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'link_text', 'View all artists' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'artists' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'why', 'Why Blossom', 80, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Why Blossom' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Personal care, down to the smallest detail' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_1_icon', 'fa-solid fa-wand-magic-sparkles' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_1_title', 'Attention to detail' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_1_text', 'Neat edges, clean lines and a finish that looks right up close.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_2_icon', 'fa-regular fa-hand' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_2_title', 'Made for your hands' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_2_text', 'Shape, length and colour chosen to suit you and your day.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_3_icon', 'fa-regular fa-heart' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_3_title', 'Relaxed appointments' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_3_text', 'One client at a time, with time to change your mind.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_4_icon', 'fa-solid fa-calendar-check' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_4_title', 'Easy online booking' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'item_4_text', 'Book online any time, or give us a call during opening hours.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'why' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'booking', 'Booking Steps', 90, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Booking' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Your next appointment is four simple steps away' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Not sure what you want yet? Book a manicure and we''ll decide together at the table.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_1_title', 'Choose your service' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_1_text', 'Manicure, nail art or anything else' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_2_title', 'Choose your artist' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_2_text', 'Or take the next free slot' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_3_title', 'Pick your date and time' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_3_text', 'Mon–Fri 9–5, Sat 9–2' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_4_title', 'Confirm your visit' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'step_4_text', 'Details arrive by message' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'booking' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'offers', 'Offers', 100, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'offers');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Booked together' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'offers' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Current offers' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'offers' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'link_text', 'View all offers' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'offers' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'testimonials', 'Reviews', 110, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'testimonials');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Reviews' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'testimonials' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'What our clients say' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'testimonials' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'location', 'Location', 120, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'location');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'pre_heading', 'Visit us' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'location' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'In the centre of Gorlice' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'location' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'instagram', 'Instagram', 130, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Latest from Instagram' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'link_text', 'Follow @blossom.gorlice' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_1', 'b23a57713d489ae8f83b51373be05412.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_2', 'baba6565a4cb9d6bf1fd90e37154d2ea.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_3', 'b02496ab17d0f33b99baf01cda665eb8.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_4', '9ba75d1a99f13b88a5e6abed21459be3.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_5', '18111ae156813eb83199295ced1ab60f.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'image_6', '2b530fac3e99efef53fceddce3fbe31b.jpg' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'instagram' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_sections` (`page_id`, `section_key`, `section_label`, `sort_order`, `status`) SELECT 1, 'final_cta', 'Final Call to Action', 140, 'Enable' WHERE NOT EXISTS (SELECT 1 FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'final_cta');
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'heading', 'Book your visit to Blossom' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'final_cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);
INSERT INTO `web_page_section_fields` (`section_id`, `locale`, `field_key`, `field_value`) SELECT `id`, 'en', 'contents', 'Pick a time that suits you and tell us what you have in mind. First visit? Let us know when you book and we''ll leave extra time to talk through shape, length and colour.' FROM `web_page_sections` WHERE `page_id` = 1 AND `section_key` = 'final_cta' ON DUPLICATE KEY UPDATE `field_value` = VALUES(`field_value`);

-- Home page meta -------------------------------------------------------------------

UPDATE `pages` SET
    `page_title` = 'Blossom Ewa Mazur — Manicure & Nail Art Studio in Gorlice',
    `meta_description` = 'Manicure, gel nails, nail art and nail care in Gorlice, Poland — plus hair, skin, makeup and waxing. 2 Piekarska Street, above the 5.10.15 store. Book by phone or online.'
WHERE `page_id` = 1;
