<?php
$isEdit = !empty($is_edit);
$id = $isEdit ? (int) $tbl_data['image_id'] : 0;
$crumb = $isEdit ? 'Edit' : 'Add';
$action = base_url('manage/'.$this->controller.'/'.($isEdit ? 'editRecord/'.$image_tour_id.'/'.$id : 'addRecord/'.$image_tour_id));
$locale = $manage_locales[$active_locale];
$translationStatus = $isEdit && !empty($translation_state['status']) ? $translation_state['status'] : 'MISSING';
$currentImage = !empty($tbl_data['image_image']) ? basename((string) $tbl_data['image_image']) : '';
$value = function ($key) use ($localized_values) { return isset($localized_values[$key]) ? htmlspecialchars((string) $localized_values[$key], ENT_QUOTES, 'UTF-8') : ''; };
?>
<?php $this->load->view('admin/partials/breadcrumb', array('items' => array(array('label' => 'Tours', 'url' => ADMIN_URL.'tours'), array('label' => $tourData['tour_name'].' Images', 'url' => ADMIN_URL.$this->controller.'/index/'.$image_tour_id), array('label' => $crumb.' '.$this->moduleNameSingular, 'active' => TRUE)))); ?>
<?php if (!empty($form_error)) { ?><div class="alert alert-danger" role="alert"><strong>Could not save the image.</strong> <?php echo htmlspecialchars($form_error, ENT_QUOTES, 'UTF-8'); ?></div><?php } ?>
<section class="admin-records-listing" aria-labelledby="tour-image-form-title"<?php if ($isEdit) { ?> data-translation-poll data-module="tour_images" data-status-url="<?php echo base_url('manage/translations/statuses'); ?>" data-poll-seconds="4" data-locale="<?php echo htmlspecialchars($active_locale, ENT_QUOTES, 'UTF-8'); ?>"<?php } ?>>
    <?php $this->load->view('admin/partials/module_header', array('title' => $tourData['tour_name'].' Images', 'description' => 'Add a gallery image and its display details.', 'id' => 'tour-image-form-title')); ?>
    <div class="card admin-card"><div class="card-header d-flex flex-wrap align-items-center justify-content-between gap-3"><h2 class="card-title mb-0"><?php echo $crumb; ?> <?php echo htmlspecialchars($this->moduleNameSingular, ENT_QUOTES, 'UTF-8'); ?></h2><?php if ($isEdit) { $this->load->view('admin/partials/manage_language_switcher', array('language_base_url' => base_url('manage/'.$this->controller.'/control/'.$image_tour_id.'/'.$id), 'locales' => $manage_locales, 'locale' => $active_locale, 'translation_module' => 'tour_images', 'translation_entity_id' => $id, 'translation_status' => $translationStatus, 'translation_ready' => $translationStatus === 'SUCCEEDED')); } ?></div><div class="card-body">
        <form id="tour-image-form" method="post" action="<?php echo $action; ?>" enctype="multipart/form-data" class="validate" novalidate data-manage-language-form data-submit-lock>
            <input type="hidden" name="active_locale" value="<?php echo htmlspecialchars($active_locale, ENT_QUOTES, 'UTF-8'); ?>"><input type="hidden" name="redirect_lang" value="" data-redirect-locale>
            <?php if ($this->config->item('csrf_protection')) { ?><input type="hidden" name="<?php echo htmlspecialchars($this->security->get_csrf_token_name(), ENT_QUOTES, 'UTF-8'); ?>" value="<?php echo htmlspecialchars($this->security->get_csrf_hash(), ENT_QUOTES, 'UTF-8'); ?>"><?php } ?>
            <div class="row"><div class="admin-field mb-3 col-md-6"><label class="form-label is-required" for="localized_name">Image Name</label><input type="text" class="form-control" name="localized_name" id="localized_name" maxlength="<?php echo $active_locale === 'ar' ? '255' : '100'; ?>" value="<?php echo $value('localized_name'); ?>" data-translation-field="localized_name" data-validate="required" required dir="<?php echo $locale['direction']; ?>"<?php echo $active_locale === 'ar' ? ' lang="ar"' : ''; ?>></div><div class="admin-field mb-3 col-md-6"><label class="form-label" for="image_status">Status</label><select class="form-select select2" name="image_status" id="image_status" data-minimum-results-for-search="-1"><option value="Enable"<?php echo !isset($tbl_data['image_status']) || $tbl_data['image_status'] === 'Enable' ? ' selected' : ''; ?>>Enabled</option><option value="Disable"<?php echo isset($tbl_data['image_status']) && $tbl_data['image_status'] === 'Disable' ? ' selected' : ''; ?>>Disabled</option></select></div></div>
            <?php $this->load->view('admin/partials/file_upload', array('name' => 'uploadfile', 'id' => 'uploadfile', 'label' => 'Image', 'allowed_types' => UPLOAD_IMAGE_MIMES, 'required' => TRUE, 'current_path' => $currentImage !== '' ? 'assets/frontend/images/tour-images/'.$currentImage : '', 'help' => 'JPG, JPEG, PNG, GIF, or WebP. Maximum size: '.UPLOAD_SIZE_MB.' MB.', 'recommended_size' => '1600 × 1200px or larger', 'size_note' => 'The gallery grid shows a centred square crop, so keep the subject in the middle. The full image opens in the lightbox, scaled to 1600px wide.', 'preview_alt' => 'Current tour image', 'preview_shape' => 'square', 'preview_size' => 180)); ?>
            <div class="admin-form-actions"><a class="btn btn-outline-secondary" href="<?php echo ADMIN_URL.$this->controller.'/index/'.$image_tour_id; ?>">Cancel</a><button type="submit" class="btn btn-primary" data-save-button><span data-save-label>Save <?php echo htmlspecialchars($this->moduleNameSingular, ENT_QUOTES, 'UTF-8'); ?></span></button></div>
        </form>
    </div></div>
</section>
<?php if ($isEdit) { $this->load->view('admin/partials/manage_language_switch_modal'); } ?>
