<?php defined('BASEPATH') or exit('No direct script access allowed');

// The site is English only. Section fields keep a locale column, so this is
// the single locale they are read and written with.
$config['content_locales'] = array(
    'en' => array('label' => 'English', 'direction' => 'ltr'),
);

$config['default_content_locale'] = 'en';
$config['content_section_image_path'] = 'assets/frontend/images/content-sections/';
$config['content_section_image_types'] = 'gif|jpg|jpeg|png|webp';
$config['content_section_image_max_kb'] = 10240;
$config['content_section_audit_path'] = APPPATH . 'logs/content_sections_audit.log';

$config['web_page_sections'] = array(
    1 => array(
        array(
            'key' => 'tours',
            'label' => 'Tours',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                // array('key' => 'background_image', 'type' => 'image', 'label' => 'Background Image', 'group' => 'Image', 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            ),
        ),
        array(
            'key' => 'discover_madinah',
            'label' => 'Discover Madinah',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'image', 'type' => 'image', 'label' => 'Image', 'group' => 'Image', 'required' => false, 'layout' => 'full', 'recommended_size' => '960 × 1200px (4:5)', 'size_note' => 'Shown in a portrait 4:5 frame. Other ratios are cropped from the centre, so keep the subject in the middle.'),
                array('key' => 'card_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_3_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_4_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Link', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Link', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Link', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Link', 'required' => false, 'layout' => 'half'),
            ),
        ),

        array(
            'key' => 'experiences',
            'label' => 'Experiences',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                // array('key' => 'background_image', 'type' => 'image', 'label' => 'Background Image', 'group' => 'Image', 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            ),
        ),

        array(
            'key' => 'why_alam_almunawara',
            'label' => 'Why Alam Al-Munawara',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'card_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_3_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_4_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_5_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_6_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 6', 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'meet_the_guides',
            'label' => 'Meet the Guides',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            ),
        ),
        array(
            'key' => 'how_booking_works',
            'label' => 'How Booking Works',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'step_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Step 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Step 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Step 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Step 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Step 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Step 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Step 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Step 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_5_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Step 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_5_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Step 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_6_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Step 6', 'required' => false, 'layout' => 'full'),
                array('key' => 'step_6_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Step 6', 'required' => false, 'layout' => 'full'),
                array('key' => 'button_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_1_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button 1', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_1_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_1_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_2_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button 2', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_2_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_2_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button 2', 'required' => false, 'layout' => 'half'),
            ),
        ),
        array(
            'key' => 'customer_reviews',
            'label' => 'Customer Reviews',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'faqs',
            'label' => 'FAQs',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),

            ),
        ),
        array(
            'key' => 'blogs',
            'label' => 'Blogs',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),

            ),
        ),
    ),
    '2' => array(
        array(
            'key' => 'alam_almunawara',
            'label' => 'Alam Al-Munawara',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'image', 'type' => 'image', 'label' => 'Image', 'group' => 'Image', 'required' => false, 'layout' => 'full', 'recommended_size' => '960 × 1200px (4:5)', 'size_note' => 'Shown in a portrait 4:5 frame. Other ratios are cropped from the centre, so keep the subject in the middle.'),
                array('key' => 'card_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Image Card', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Image Card', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Image Card', 'required' => false, 'layout' => 'full'),

            ),
        ),
        array(
            'key' => 'our_approach',
            'label' => 'Our Approach',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'card_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_3_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_4_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_5_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_6_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 6', 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'knowledge_matters',
            'label' => 'Why Local Knowledge Matters',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'image', 'type' => 'image', 'label' => 'Image', 'group' => 'Image', 'required' => false, 'layout' => 'full', 'recommended_size' => '960 × 1200px (4:5)', 'size_note' => 'Shown in a portrait 4:5 frame. Other ratios are cropped from the centre, so keep the subject in the middle.'),
                array('key' => 'reason_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Reason 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reason 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Reason 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'reason_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Reason 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reason 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Reason 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'reason_3_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Reason 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reason 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Reason 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'reason_4_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Reason 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reason 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Reason 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'reason_5_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Reason 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_5_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reason 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_5_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Reason 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'reason_6_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Reason 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_6_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reason 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'reason_6_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Reason 6', 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'guiding_principles',
            'label' => 'Guiding Principles',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'card_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_3_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_4_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_5_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_6_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 6', 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'meet_the_guides',
            'label' => 'Meet the Guides',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            ),
        ),

        array(
            'key' => 'experiences',
            'label' => 'Experiences',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                // array('key' => 'background_image', 'type' => 'image', 'label' => 'Background Image', 'group' => 'Image', 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            ),
        ),

        array(
            'key' => 'tours',
            'label' => 'Tours',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                // array('key' => 'background_image', 'type' => 'image', 'label' => 'Background Image', 'group' => 'Image', 'required' => false, 'layout' => 'full'),
                array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            ),
        ),
    ),
    '3' => array(
        array(
            'key' => 'search_filters',
            'label' => 'Search & Filters',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    '4' => array(
        array(
            'key' => 'search_filters',
            'label' => 'Search & Filters',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    '5' => array(
        array(
            'key' => 'plan_your_visit_form',
            'label' => 'Plan Your Visit Form',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'audience_fit',
            'label' => 'Audience Fit',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'card_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 1', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_1_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 1', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 2', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_2_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 2', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_3_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 3', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_3_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 3', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_4_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 4', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_4_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 4', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_5_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 5', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_5_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 5', 'required' => false, 'layout' => 'full'),
                array('key' => 'card_6_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Card 6', 'required' => false, 'layout' => 'half'),
                array('key' => 'card_6_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Card 6', 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    '7' => array(
        array(
            'key' => 'contact_form',
            'label' => 'Contact Form',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'contact_form_privacy',
            'label' => 'Contact Form Privacy Contents',
            'fields' => array(
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    '11' => array(
        array(
            'key' => 'search_filters',
            'label' => 'Search & Filters',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'text-editor', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    // Services (/services). The hero comes from the page's banner fields.
    37 => array(
        array(
            'key' => 'featured_services',
            'label' => 'Featured Services',
            'fields' => array(
                array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
            ),
        ),
        array(
            'key' => 'full_menu',
            'label' => 'Full Menu',
            'fields' => array(
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'cta',
            'label' => 'Call to Action',
            'fields' => array(
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    // Gallery (/gallery). The hero comes from the page's banner fields.
    39 => array(
        array(
            'key' => 'hero_link',
            'label' => 'Hero Button',
            'fields' => array(
                array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => null, 'required' => false, 'layout' => 'half'),
                array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => null, 'required' => false, 'layout' => 'half'),
            ),
        ),
        array(
            'key' => 'cta',
            'label' => 'Call to Action',
            'fields' => array(
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
    // Artists (/artists). The hero comes from the page's banner fields; the
    // first artist in Manage > Artists is shown as the lead artist.
    38 => array(
        array(
            'key' => 'team',
            'label' => 'Team',
            'fields' => array(
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
                array('key' => 'placeholder_note', 'type' => 'textarea', 'label' => 'Note shown while placeholder profiles are listed', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
        array(
            'key' => 'cta',
            'label' => 'Call to Action',
            'fields' => array(
                array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
                array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            ),
        ),
    ),
);

$config['miscellaneous_content_sections'] = array(
    // Headings and call to action shared by every artist page (/artists/{slug}).
    array(
        'key' => 'artist_page',
        'label' => 'Artist Page',
        'fields' => array(
            array('key' => 'services_heading', 'type' => 'text', 'label' => 'Services Heading ({name} is replaced by the first name)', 'group' => 'Services', 'required' => true, 'layout' => 'full'),
            array('key' => 'days_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Working Days', 'required' => false, 'layout' => 'half'),
            array('key' => 'days_button', 'type' => 'text', 'label' => 'Button Text', 'group' => 'Working Days', 'required' => false, 'layout' => 'half'),
            array('key' => 'days_note', 'type' => 'textarea', 'label' => 'Note', 'group' => 'Working Days', 'required' => false, 'layout' => 'full'),
            array('key' => 'work_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Recent Work', 'required' => false, 'layout' => 'half'),
            array('key' => 'work_button', 'type' => 'text', 'label' => 'Button Text', 'group' => 'Recent Work', 'required' => false, 'layout' => 'half'),
            array('key' => 'work_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Recent Work', 'required' => false, 'layout' => 'full'),
            array('key' => 'reviews_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Reviews', 'required' => false, 'layout' => 'half'),
            array('key' => 'reviews_note', 'type' => 'textarea', 'label' => 'Note', 'group' => 'Reviews', 'required' => false, 'layout' => 'full'),
            array('key' => 'cta_heading', 'type' => 'text', 'label' => 'Heading ({name} is replaced by the first name)', 'group' => 'Call to Action', 'required' => true, 'layout' => 'full'),
            array('key' => 'cta_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Call to Action', 'required' => false, 'layout' => 'full'),
        ),
    ),
    // Headings and call to action shared by every service page (/services/{slug}).
    array(
        'key' => 'service_page',
        'label' => 'Service Page',
        'fields' => array(
            array('key' => 'included_heading', 'type' => 'text', 'label' => 'What\'s Included Heading', 'group' => 'Details', 'required' => true, 'layout' => 'half'),
            array('key' => 'before_heading', 'type' => 'text', 'label' => 'Before Your Visit Heading', 'group' => 'Details', 'required' => false, 'layout' => 'half'),
            array('key' => 'aftercare_heading', 'type' => 'text', 'label' => 'Aftercare Heading', 'group' => 'Details', 'required' => false, 'layout' => 'half'),
            array('key' => 'addons_heading', 'type' => 'text', 'label' => 'Add-ons Heading', 'group' => 'Add-ons', 'required' => false, 'layout' => 'half'),
            array('key' => 'addons_note', 'type' => 'text', 'label' => 'Add-ons Note', 'group' => 'Add-ons', 'required' => false, 'layout' => 'full'),
            array('key' => 'gallery_heading', 'type' => 'text', 'label' => 'Gallery Heading', 'group' => 'Related Content', 'required' => false, 'layout' => 'third'),
            array('key' => 'artists_heading', 'type' => 'text', 'label' => 'Artists Heading', 'group' => 'Related Content', 'required' => false, 'layout' => 'third'),
            array('key' => 'related_heading', 'type' => 'text', 'label' => 'Related Services Heading', 'group' => 'Related Content', 'required' => false, 'layout' => 'third'),
            array('key' => 'cta_heading', 'type' => 'text', 'label' => 'Heading ({service} is replaced by the service name)', 'group' => 'Call to Action', 'required' => true, 'layout' => 'full'),
            array('key' => 'cta_text', 'type' => 'textarea', 'label' => 'Text', 'group' => 'Call to Action', 'required' => false, 'layout' => 'full'),
        ),
    ),
    array(
        'key' => 'get_in_touch',
        'label' => 'Get In Touch',
        'fields' => array(
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
        ),
    ),
    array(
        'key' => 'where_we_are',
        'label' => 'Where We Are',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'call_or_message',
        'label' => 'Call or Message',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'email_us',
        'label' => 'Email Us',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'still_need_help',
        'label' => 'Still Need Help?',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'browse_tours',
        'label' => 'Browse the tours',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'talk_to_us',
        'label' => 'Talk to Us',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'plan_with_us',
        'label' => 'Plan with Us',
        'fields' => array(
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_1_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button 1', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_1_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button 1', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_1_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button 1', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_1_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button 1', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_2_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button 2', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_2_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button 2', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_2_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button 2', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_2_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button 2', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'featured_posts',
        'label' => 'Featured Posts',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
             array('key' => 'link_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Link', 'required' => false, 'layout' => 'half'),
            array('key' => 'link_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Link', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'link_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Link', 'required' => false, 'layout' => 'half'),
            array('key' => 'link_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Link', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'privacy_policy_card',
        'label' => 'Privacy Policy Card',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'cancellation_policy_card',
        'label' => 'Cancellation Policy Card',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'need_help_choosing',
        'label' => 'Need help choosing?',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'prefer_to_talk',
        'label' => 'Prefer to Talk?',
        'fields' => array(
            array('key' => 'icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => false, 'layout' => 'third'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Contents', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'button_icon', 'type' => 'icon-picker', 'label' => 'Icon', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_icon_pos', 'type' => 'select', 'label' => 'Icon Position', 'group' => 'Button', 'required' => false, 'layout' => 'half', 'options' => array('Left' => 'Left', 'Right' => 'Right')),
            array('key' => 'button_text', 'type' => 'text', 'label' => 'Text', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
            array('key' => 'button_url', 'type' => 'text', 'label' => 'URL', 'group' => 'Button', 'required' => false, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'tour_navigation',
        'label' => 'Tour / Experience Navigation',
        'fields' => array(
            array('key' => 'overview', 'type' => 'text', 'label' => 'Overview', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'places', 'type' => 'text', 'label' => 'Places & Highlights', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'itinerary', 'type' => 'text', 'label' => 'Itinerary', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'practical_information', 'type' => 'text', 'label' => 'Practical Information', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'gallery', 'type' => 'text', 'label' => 'Gallery', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'vehicles', 'type' => 'text', 'label' => 'Vehicles', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'guides', 'type' => 'text', 'label' => 'Guides', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'faqs', 'type' => 'text', 'label' => 'FAQs', 'group' => null, 'required' => true, 'layout' => 'half'),
        ),
    ),
    array(
        'key' => 'tour_price_details',
        'label' => 'Price Details',
        'fields' => array(
            array('key' => 'tour', 'type' => 'textarea', 'label' => 'Tour', 'group' => null, 'required' => false, 'layout' => 'half'),
            array('key' => 'experience', 'type' => 'textarea', 'label' => 'Experience', 'group' => null, 'required' => false, 'layout' => 'half'),
        ),
    ),
    // Shown on the services with "Show shapes and finishes" ticked (Manage > Services).
    array(
        'key' => 'nail_shapes_finishes',
        'label' => 'Nail Shapes & Finishes',
        'fields' => array(
            array('key' => 'pre_heading', 'type' => 'text', 'label' => 'Pre-Heading', 'group' => null, 'required' => false, 'layout' => 'half'),
            array('key' => 'heading', 'type' => 'text', 'label' => 'Heading', 'group' => null, 'required' => true, 'layout' => 'half'),
            array('key' => 'contents', 'type' => 'textarea', 'label' => 'Introduction', 'group' => null, 'required' => false, 'layout' => 'full'),
            array('key' => 'shapes_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Shapes', 'required' => false, 'layout' => 'half'),
            array('key' => 'shapes', 'type' => 'textarea', 'label' => 'Shapes (one per line: Name | Description)', 'group' => 'Shapes', 'required' => false, 'layout' => 'full'),
            array('key' => 'finishes_heading', 'type' => 'text', 'label' => 'Heading', 'group' => 'Finishes', 'required' => false, 'layout' => 'half'),
            array('key' => 'finishes', 'type' => 'textarea', 'label' => 'Finishes (one per line: Name | Description | #colour)', 'group' => 'Finishes', 'required' => false, 'layout' => 'full'),
        ),
    ),
);
